project_name: echo-http
dist: .bin
builds:
  - id: echo-http
    binary: "echo-http"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"

archives:
  - id: echo-http
    name_template: >-
      {{.ProjectName}}_
      {{- .Tag}}_
      {{- if eq .Os "darwin"}}macos
      {{- else if eq .Os "windows"}}win
      {{- else}}{{.Os}}{{end}}_
      {{- if eq .Arch "amd64"}}x86_64
      {{- else if eq .Arch "386"}}i386
      {{- else}}{{.Arch}}{{end}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
    rlcp: true


brews:
  -
    name: echo-http
    tap:
      owner: umputun
      name: homebrew-apps
      branch: master
    commit_author:
      name: umputun
      email: umputun@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://echo-http.umputun.dev/"
    description: "Responds with json-formatted echo of the incoming request and with a predefined message."
    license: "MIT"

nfpms:
  - id: echo-http
    package_name: echo-http
    file_name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    vendor: Umputun
    homepage: https://echo-http.umputun.dev
    maintainer: Umputun <umputun@gmail.com>
    description: Responds with json-formatted echo of the incoming request and with a predefined message
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    epoch: 1
    release: 1
